version: '2'
services:
    wordpress:
        image: wordpress:latest 
        ports:
        - 127.0.0.1:80:80 # you can change ip
        volumes:
        - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        - ./wp-app:/var/www/html # wordpress files
        - ./plugins/:/var/www/html/wp-content/plugins/ # custom plugin
        - ./themes/:/var/www/html/wp-content/themes/ # custom theme
        - ./uploads/:/var/www/html/wp-content/uploads/ # custom uploads
       

        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: password
        depends_on:
        - db
        - mailhog

        networks:
        - wordpress-network

    db:
        image: mysql:5.7 # https://hub.docker.com/_/mysql/ // mariadb https://hub.docker.com/_/mariadb
        ports:
        - 127.0.0.1:3307:3306 # you can change ip
        restart: always
        command: [
            '--default_authentication_plugin=mysql_native_password',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
        ]
        volumes:
        - ./wp-data:/var/lib/mysql

        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: password
        networks:
        - wordpress-network

    phpmyadmin:
        depends_on:
        - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
        - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        networks:
        - wordpress-network


    mailhog:
        image: mailhog/mailhog
        ports:
        - 1025:1025
        - 8025:8025

    wpcli:
        image: tatemz/wp-cli
        volumes_from:
        - wordpress
        links:
        - db:mysql
        command: "sh wp.sh"


networks:
    wordpress-network:
        driver: bridge
